In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/1-8.화성시_성연령별_유동인구.csv')

In [3]:
len(df)

5269124

In [4]:
df1 = df.copy()

In [5]:
df1.head()

STD_YM  m_10g_pop  m_20g_pop  m_30g_pop  m_40g_pop  m_50g_pop  m_60g_pop  \
0  202001       0.26       0.58       0.86       1.06       1.26       1.29   
1  202001       0.25       0.56       0.83       1.05       1.18       1.23   
2  202001       0.30       0.68       0.95       1.17       1.42       1.40   
3  202001       0.34       0.76       1.04       1.25       1.56       1.53   
4  202001       0.22       0.67       0.99       1.51       1.87       1.77   

   w_10g_pop  w_20g_pop  w_30g_pop  w_40g_pop  w_50g_pop  w_60g_pop  \
0       0.27       0.56       0.69       0.81       1.13       1.34   
1       0.27       0.56       0.62       0.81       1.11       1.17   
2       0.32       0.67       0.74       0.93       1.22       1.34   
3       0.36       0.75       0.79       1.03       1.34       1.46   
4       0.20       0.56       0.76       1.26       1.73       1.65   

          lon        lat  
0  126.616734  37.169078  
1  126.616729  37.169528  
2  126.616724  37.169979  
3  126.616718  37.170430  
4  126.616713  37.170880

In [6]:
df1['STD_YM'].unique()

array([202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008,
       202009, 202010, 202011, 202012, 202101, 202102, 202103, 202104,
       202105, 202106, 202107, 202108, 202109, 202110, 202111, 202112,
       202201, 202202, 202203, 202204, 202205, 202206, 202207, 202208,
       202209, 202210, 202211, 202212])

In [7]:
df1_2020 = df1[df1['STD_YM'].between(202001, 202012)]

In [8]:
df1_2020['STD_YM'].unique()

array([202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008,
       202009, 202010, 202011, 202012])

In [9]:
df1_2021 = df1[df1['STD_YM'].between(202101, 202112)]

In [10]:
df1_2021['STD_YM'].unique()

array([202101, 202102, 202103, 202104, 202105, 202106, 202107, 202108,
       202109, 202110, 202111, 202112])

In [11]:
df1_2022 = df1[df1['STD_YM'].between(202201, 202212)]

In [12]:
df1_2022['STD_YM'].unique()

array([202201, 202202, 202203, 202204, 202205, 202206, 202207, 202208,
       202209, 202210, 202211, 202212])

In [13]:
df1_2020.to_csv('../data/화성시 성연령별유동인구_2020.csv', index=False)

In [14]:
df1_2021.to_csv('../data/화성시 성연령별유동인구_2021.csv', index=False)

In [15]:
df1_2022.to_csv('../data/화성시 성연령별유동인구_2022.csv', index=False)