In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/1-9.화성시_시간대별_유동인구.csv')

In [3]:
len(df)

5168678

In [4]:
df1 = df.copy()

In [5]:
df1['STD_YM'].unique()

array([202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008,
       202009, 202010, 202011, 202012, 202101, 202102, 202103, 202104,
       202105, 202106, 202107, 202108, 202109, 202110, 202111, 202112,
       202201, 202202, 202203, 202204, 202205, 202206, 202207, 202208,
       202209, 202210, 202211, 202212])

In [6]:
df1_2020 = df1[df1['STD_YM'].between(202001, 202012)]

In [7]:
df1_2020['STD_YM'].unique()

array([202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008,
       202009, 202010, 202011, 202012])

In [8]:
df1_2021 = df1[df1['STD_YM'].between(202101, 202112)]

In [9]:
df1_2021['STD_YM'].unique()

array([202101, 202102, 202103, 202104, 202105, 202106, 202107, 202108,
       202109, 202110, 202111, 202112])

In [10]:
df1_2022 = df1[df1['STD_YM'].between(202201, 202212)]

In [11]:
df1_2022['STD_YM'].unique()

array([202201, 202202, 202203, 202204, 202205, 202206, 202207, 202208,
       202209, 202210, 202211, 202212])

In [12]:
df1_2020.to_csv('../data/화성시 시간대별유동인구_2020.csv', index=False)

In [13]:
df1_2021.to_csv('../data/화성시 시간대별유동인구_2021.csv', index=False)

In [14]:
df1_2022.to_csv('../data/화성시 시간대별유동인구_2022.csv', index=False)